from setuptools import setup, find_packages

setup(
    name="rc_mamba",
    version="0.1.0",
    packages=find_packages(),
    description="Retrieval‑Conditioned Mamba with FiLM, dynamic retrieval, and dual‑codebook quantization",
    author="RC-Mamba Research Team",
    author_email="",
    install_requires=[
        "torch>=2.0.0",
        "transformers>=4.30.0",
        "datasets>=2.12.0",
        "numpy>=1.24.0",
        "scipy>=1.10.0",
        "einops>=0.6.1",
        "wandb>=0.15.0",
        "faiss-cpu>=1.7.4",
        "pillow>=9.5.0",
        "librosa>=0.10.0",
        "accelerate>=0.20.0",
        "peft>=0.4.0",
        "trl>=0.4.7",
        "matplotlib>=3.7.0",
        "seaborn>=0.12.0",
        "pytest>=7.3.0",
        "jupyter>=1.0.0",
        "tqdm>=4.65.0",
        "omegaconf>=2.3.0",
        "hydra-core>=1.3.0",
        "sentence-transformers>=2.2.0",
        "mamba-ssm>=1.1.0",
        "causal-conv1d>=1.1.0",
        "timm>=0.9.0",
        "clip-by-openai>=1.0.0",
        "gradio>=3.35.0",
        "scikit-learn>=1.3.0",
        "tokenizers>=0.13.3",
        "evaluate>=0.4.0",
    ],
    python_requires=">=3.8",
)